  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.23.0 # https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/3702
    container_name: otel-logzio
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yml:ro
    ports:
      - "4317:4317" # OTLP gRPC receiver